import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Visual Delights | About",
  description: "Generated by create next app",
};

const Layout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return <div>{children}</div>;
};

export default Layout;
