import {
  AbsoluteCenter,
  Grid,
  GridItem,
  HStack,
  Heading,
  Divider,
  Text,
} from "@chakra-ui/layout";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Provider } from "./provider";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Grid
            templateAreas={` "Nav" "Display" "Footer" `}
            templateRows={`repeat(20,1fr)`}
            templateColumns={`repeat(1,1fr)`}
            h={"100vh"}
          >
            <Navbar />
            <Grid
              as={GridItem}
              area={"Display"}
              style={{
                backgroundColor: `transparent`,
              }}
              rowSpan={16}
              colSpan={1}
              // templateAreas={`"sect1 sect2"`}
              // templateColumns={`repeat(1,1fr)`}
              // templateRows={`repeat(1,1fr)`}
              h={"90vh"}
            >
              {children}
            </Grid>
            <Footer />
          </Grid>
        </Provider>
      </body>
    </html>
  );
}
